#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm_contrib/verification_other/global_oce_llc90/input_ad.core2/prepare_run,v 1.4 2017/03/01 22:35:45 jmc Exp $
#  $Name:  $

../input.core2/prepare_run

