#!/bin/csh -f

set dirLlc = ../
set dirCs32 = ../../global_oce_cs32/

ln -s ${dirLlc}/input_ad.core2/* .
ln -s ${dirLlc}/input_ad/* .
ln -s ${dirLlc}/input/* .
ln -s ${dirCs32}/input/* .
ln -s ${dirLlc}/input_fields/* .
\rm CORE2*1992
ln -s ${dirLlc}/input_fields/core2/* .

mkdir DIAGfiles
mkdir ADJfiles
mkdir diags
mkdir tapes

