#!/bin/csh -f

set dirInputFields  = ../../global_oce_input_fields/
set dirLlc90        = ../../global_oce_llc90/
set dirCs32         = ../../global_oce_cs32/

ln -s ${dirCs32}/input/* .
ln -s ${dirInputFields}/cs32/* .
${dirLlc90}/input/prepare_run

