#!/bin/csh -f

set dirInputFields  = ../input_fields/
set dirLlc90        = ../../global_oce_llc90/
set dirCs32         = ../../global_oce_cs32/

ln -s ${dirCs32}/input/* .
ln -s ${dirInputFields}/* .
${dirLlc90}/input/prepare_run

