#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm_contrib/verification_other/global_oce_biogeo_bling/input/prepare_run,v 1.1 2016/05/23 18:41:57 jmc Exp $
#  $Name:  $
 
#- in order to save disc space, take *.bin files
#- from this dir:
fromDir="../../../verification/tutorial_global_oce_biogeo/input"

fileList=`( cd $fromDir ; echo *.bin )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
