#!/bin/bash

# $Header: /u/gcmpack/MITgcm_contrib/verification_other/cpl_gray+ocn/build_ocn/genmake_local,v 1.1 2013/09/25 19:31:00 jmc Exp $

#  This is the local options file for the "new" version of genmake
#
#  EH3 initial version 2003-08

MODS="../code_ocn ../shared_code"
