#!/bin/bash

# $Header: /u/gcmpack/MITgcm_contrib/verification_other/cpl_gray+ocn/build_cpl/genmake_local,v 1.1 2013/09/25 19:30:59 jmc Exp $

#  This is the local options file for the "new" version of genmake
#
#  EH3 initial version 2003-08

STANDARDDIRS=""

MODS="../code_cpl ../shared_code"
