#!/bin/csh -f

set dirInputFields  = ../../global_oce_input_fields/
set dirLlc90        = ../../global_oce_llc90/

ln -s ${dirLlc90}/input.ecmwf/* .
ln -s ${dirInputFields}/ecmwf/* .
${dirLlc90}/input/prepare_run

