#! /usr/bin/env bash

dirList="../input"

for fromDir in $dirList
do

#- and do a symbolic link in the current directory
#   (if the file does not already exist)
if test -d $fromDir ; then
  fileList="eedata data.cal data.cost data.ecco data.exch2 data.exf data.ggl90 data.optim data.profiles"
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then
      if test ! -r $xx ; then
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
done

#- and link input-file (as currently done for forward primary test):
../input/prepare_run

