#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm_contrib/verification_other/global_oce_llc90/input_ad.ecmwf/prepare_run,v 1.4 2017/03/01 22:35:45 jmc Exp $
#  $Name:  $

../input.ecmwf/prepare_run

