#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm_contrib/verification_other/global_oce_llc90/input_ad.ecco_v4/prepare_run,v 1.8 2017/03/01 22:35:45 jmc Exp $
#  $Name:  $

../input.ecco_v4/prepare_run

