#!/bin/csh -f

set dirLlc = ../
set dirCs32 = ../../global_oce_cs32/

ln -s ${dirLlc}/input_ad.ecco_v4/* .
ln -s ${dirLlc}/input_ad/* .
ln -s ${dirLlc}/input/* .
ln -s ${dirCs32}/input/* .
ln -s ${dirLlc}/input_fields/* .
ln -s ${dirLlc}/input_fields/ecmwf/* .
ln -s ${dirLlc}/input_fields/ecco_v4/* .

mkdir DIAGfiles
mkdir ADJfiles
mkdir diags
mkdir tapes

