#! /usr/bin/env bash

#- first take few parameter files from main input dir (i.e., ../input):
fromDir="../input"
#  and do a symbolic link in the current directory (if the file does not already exist)
fileList="eedata data.cost data.exch2 data.ggl90 data.optim data.profiles"

if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then
      if test ! -r $xx ; then
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

#- take other parameter files from forward-test input dir (i.e., from ../input.ecco_v4/)
fromDir="../input.ecco_v4"
#  and do a symbolic link in the current directory (if the file does not already exist)
fileList="data.cal data.ecco data.exf data.gmredi data.seaice"

if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then
      if test ! -r $xx ; then
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

#- and take other bin files using forward-test prepare_run (from ../input.ecco_v4):
if test -x ${fromDir}/prepare_run ; then
  ${fromDir}/prepare_run
fi
