#!/bin/csh -f

set dirInputFields  = ../../global_oce_input_fields/
set dirLlc90        = ../../global_oce_llc90/
set dirCs32         = ../../global_oce_cs32/

#ln -s ${dirCs32}/input_ad/* .
${dirCs32}/input/prepare_run

