#!/bin/csh -f

set dirInputFields  = ../../global_oce_input_fields/
set dirLlc90        = ../../global_oce_llc90/
set dirCs32         = ../../global_oce_cs32/

ln -s ${dirCs32}/input_fields/CORE* .
ln -s ${dirLlc90}/input/* .
ln -s ${dirInputFields}/* .
ln -s ${dirInputFields}/llc90/* .
ln -s ${dirInputFields}/llc90_fields/* .
ln -s ${dirInputFields}/llc90_runoff/* .

mkdir diags
mkdir tapes

