#!/bin/csh -f

set dirLlc = ../
set dirCs32 = ../../global_oce_cs32/

ln -s ${dirLlc}/input/* .
ln -s ${dirCs32}/input/* .
ln -s ${dirCs32}/input_fields/CORE* .
ln -s ${dirLlc}/input_fields/* .

mkdir DIAGfiles
mkdir ADJfiles
mkdir diags
mkdir tapes

